[package]
name = "test_project"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "1.0", features = ["full"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11.5"
ntest = "0.7.2"
libc = "0.2"